### ISSUE TITLE
Incorrect comparison in readme

### ISSUE THREAD

**Issue by lukechilds** [dpc/rust-bitcoin-indexer#10]
>Embedded KV store can be potentially more compact and faster, but electrs stores the actual block data, while rust-bitcoin-indexer extracts only the data it needs and throws everything else away.

I'm not sure this is correct. As far as I understand it electrs only maintains a very minimal TX output, TX input and TXID => block height index.

All the actual data queries are passed through to bitcoind.

https://github.com/romanz/electrs/blob/0f3aaa6671e3839fc2dcdc54a36f0e8dd674f398/doc/schema.md

**Comment by dpc** [comment]
Oh. My bad. So they only keep additional indices around? That will work too (not sure about performance, but I guess full node should respond pretty much like a remote db, so should be good enough). Thanks for pointing it out!

**Comment by dpc** [comment]
I modified https://github.com/dpc/rust-bitcoin-indexer/blob/master/README.md#vs-electrs . If anything is still incorrectly, let me know. Thanks again!
